// songs.js
const songs = [
  // === THE SPECIFIC REQUESTS (5 songs) ===
  { id: 1, title: "Kaikai Kitan", artist: "Eve", album: "Jujutsu Kaisen Season 1 Opening", duration: "3:39", genre: "Anime J-Rock", },
  { id: 2, title: "Ao no Sumika (Where Our Blue Is)", artist: "Tatsuya Kitani", album: "Jujutsu Kaisen Season 2 Opening", duration: "3:17", genre: "Anime J-Rock" },
  { id: 3, title: "LEveL", artist: "SawanoHiroyuki[nZk]:TOMORROW X TOGETHER", album: "Solo Leveling Season 1 Opening", duration: "3:11", genre: "Anime J-Pop" },
  { id: 4, title: "ReawakeR", artist: "LiSA ft. Felix of Stray Kids", album: "Solo Leveling Season 2 Opening", duration: "3:25", genre: "Anime J-Rock" },
  { id: 5, title: "You Can't Run From Your Soul", artist: "AURORA", album: "League of Legends: Wild Rift", duration: "3:10", genre: "Dark Pop" },

  // === ASAKE (25 songs - Exactly 25%) ===
  { id: 6, title: "Lonely At The Top", artist: "Asake", album: "Work Of Art", duration: "2:37", genre: "Afrobeats" },
  { id: 7, title: "Amapiano", artist: "Asake ft. Olamide", album: "Work Of Art", duration: "2:45", genre: "Afrobeats" },
  { id: 8, title: "Active", artist: "Asake ft. Travis Scott", album: "Lungu Boy", duration: "2:51", genre: "Afrobeats" },
  { id: 9, title: "Wave", artist: "Asake ft. Central Cee", album: "Lungu Boy", duration: "2:35", genre: "Afrobeats" },
  { id: 10, title: "Organise", artist: "Asake", album: "Mr. Money With The Vibe", duration: "2:03", genre: "Afrobeats" },
  { id: 11, title: "Joha", artist: "Asake", album: "Mr. Money With The Vibe", duration: "2:28", genre: "Afrobeats" },
  { id: 12, title: "Terminator", artist: "Asake", album: "Mr. Money With The Vibe", duration: "2:36", genre: "Afrobeats" },
  { id: 13, title: "2:30", artist: "Asake", album: "Work Of Art", duration: "2:18", genre: "Afrobeats" },
  { id: 14, title: "Omo Ope", artist: "Asake ft. Olamide", album: "Mr. Money With The Vibe", duration: "2:40", genre: "Afrobeats" },
  { id: 15, title: "Sunshine", artist: "Asake", album: "Lungu Boy", duration: "3:02", genre: "Afrobeats" },
  { id: 16, title: "Suru", artist: "Asake ft. Stormzy", album: "Lungu Boy", duration: "2:55", genre: "Afrobeats" },
  { id: 17, title: "Remember", artist: "Asake", album: "Work Of Art", duration: "2:58", genre: "Afrobeats" },
  { id: 18, title: "M$NEY", artist: "Asake", album: "M$NEY", duration: "2:24", genre: "Afrobeats" },
  { id: 19, title: "Worship", artist: "Asake", album: "M$NEY", duration: "2:41", genre: "Afrobeats" },
  { id: 20, title: "Basquiat", artist: "Asake", album: "Work Of Art", duration: "2:14", genre: "Afrobeats" },
  { id: 21, title: "Sungba", artist: "Asake ft. Burna Boy", album: "Mr. Money With The Vibe", duration: "3:00", genre: "Afrobeats" },
  { id: 22, title: "Dupe", artist: "Asake", album: "Mr. Money With The Vibe", duration: "2:43", genre: "Afrobeats" },
  { id: 23, title: "Nzaza", artist: "Asake", album: "Mr. Money With The Vibe", duration: "3:03", genre: "Afrobeats" },
  { id: 24, title: "Mogbe", artist: "Asake", album: "Work Of Art", duration: "2:50", genre: "Afrobeats" },
  { id: 25, title: "Great Guy", artist: "Asake", album: "Work Of Art", duration: "2:31", genre: "Afrobeats" },
  { id: 26, title: "Awodi", artist: "Asake", album: "Work Of Art", duration: "2:48", genre: "Afrobeats" },
  { id: 27, title: "Ototo", artist: "Asake", album: "Mr. Money With The Vibe", duration: "2:38", genre: "Afrobeats" },
  { id: 28, title: "Dull", artist: "Asake", album: "Mr. Money With The Vibe", duration: "1:40", genre: "Afrobeats" },
  { id: 29, title: "What's Up My G", artist: "Asake", album: "Work Of Art", duration: "2:51", genre: "Afrobeats" },
  { id: 30, title: "Trabaye", artist: "Asake", album: "Ololade Asake - EP", duration: "2:12", genre: "Afrobeats" },

  // === THE AFROBEATS SHARE (40 songs) ===
  { id: 31, title: "Last Last", artist: "Burna Boy", album: "Love, Damini", duration: "2:52", genre: "Afrobeats" },
  { id: 32, title: "Ye", artist: "Burna Boy", album: "Outside", duration: "3:51", genre: "Afrobeats" },
  { id: 33, title: "On On", artist: "Burna Boy", album: "I Told Them...", duration: "3:07", genre: "Afrobeats" },
  { id: 34, title: "City Boys", artist: "Burna Boy", album: "I Told Them...", duration: "2:33", genre: "Afrobeats" },
  { id: 35, title: "Essence", artist: "Wizkid ft. Tems", album: "Made in Lagos", duration: "4:08", genre: "Afrobeats" },
  { id: 36, title: "Ojuelegba", artist: "Wizkid", album: "Ayo", duration: "3:36", genre: "Afrobeats" },
  { id: 37, title: "Kese (Dance)", artist: "Wizkid", album: "Morayo", duration: "2:52", genre: "Afrobeats" },
  { id: 38, title: "Unavailable", artist: "Davido ft. Musa Keys", album: "Timeless", duration: "2:50", genre: "Afrobeats" },
  { id: 39, title: "Feel", artist: "Davido", album: "Timeless", duration: "2:34", genre: "Afrobeats" },
  { id: 40, title: "Fall", artist: "Davido", album: "A Good Time", duration: "4:00", genre: "Afrobeats" },
  { id: 41, title: "Calm Down", artist: "Rema", album: "Rave & Roses", duration: "3:39", genre: "Afrobeats" },
  { id: 42, title: "Benin Boys", artist: "Rema ft. Shallipopi", album: "HEIS", duration: "2:46", genre: "Afrobeats" },
  { id: 43, title: "Ozeba", artist: "Rema", album: "HEIS", duration: "2:20", genre: "Afrobeats" },
  { id: 44, title: "Soso", artist: "Omah Lay", album: "Boy Alone", duration: "3:03", genre: "Afrobeats" },
  { id: 45, title: "Holy Ghost", artist: "Omah Lay", album: "Boy Alone: Deluxe", duration: "3:06", genre: "Afrobeats" },
  { id: 46, title: "Understand", artist: "Omah Lay", album: "Boy Alone", duration: "2:54", genre: "Afrobeats" },
  { id: 47, title: "Elon Musk", artist: "Shallipopi", album: "Presido La Pluto", duration: "3:11", genre: "Afrobeats" },
  { id: 48, title: "Cast", artist: "Shallipopi ft. Odumodublvck", album: "Presido La Pluto", duration: "2:48", genre: "Afrobeats" },
  { id: 49, title: "Declan Rice", artist: "Odumodublvck", album: "EZIOKWU", duration: "2:35", genre: "Afrobeats" },
  { id: 50, title: "Blood On The Dance Floor", artist: "Odumodublvck ft. Bloody Civilian", album: "EZIOKWU", duration: "3:10", genre: "Afrobeats" },
  { id: 51, title: "Bandana", artist: "Fireboy DML ft. Asake", album: "Playboy", duration: "2:58", genre: "Afrobeats" },
  { id: 52, title: "Peru", artist: "Fireboy DML & Ed Sheeran", album: "Playboy", duration: "3:07", genre: "Afrobeats" },
  { id: 53, title: "Chance (Na Ham)", artist: "Seyi Vibez", album: "Billion Dollar Baby", duration: "2:41", genre: "Afrobeats" },
  { id: 54, title: "Gwagwalada", artist: "BNXN ft. Kizz Daniel & Seyi Vibez", album: "Sincerely, Benson", duration: "3:15", genre: "Afrobeats" },
  { id: 55, title: "Cough (Odo)", artist: "Kizz Daniel", album: "Maverick", duration: "2:56", genre: "Afrobeats" },
  { id: 56, title: "Buga (Lo Lo Lo)", artist: "Kizz Daniel ft. Tekno", album: "Maverick", duration: "3:03", genre: "Afrobeats" },
  { id: 57, title: "Soweto", artist: "Victony ft. Tempoe", album: "Outlaw", duration: "2:28", genre: "Afrobeats" },
  { id: 58, title: "Rush", artist: "Ayra Starr", album: "19 & Dangerous", duration: "3:05", genre: "Afrobeats" },
  { id: 59, title: "Commence", artist: "Ayra Starr", album: "The Year I Turned 21", duration: "2:38", genre: "Afrobeats" },
  { id: 60, title: "Love Nwantiti", artist: "Ckay", album: "Ckay the First", duration: "2:26", genre: "Afrobeats" },
  { id: 61, title: "No Wahala", artist: "1da Banton", album: "Original Vibe Machine", duration: "2:51", genre: "Afrobeats" },
  { id: 62, title: "High", artist: "Adekunle Gold ft. Davido", album: "Catch Me If You Can", duration: "3:13", genre: "Afrobeats" },
  { id: 63, title: "Ogechi", artist: "Brown Joel ft. Davido", album: "Single", duration: "3:16", genre: "Afrobeats" },
  { id: 64, title: "Finesse", artist: "Pheelz ft. BNXN", album: "Pheelz Good", duration: "2:33", genre: "Afrobeats" },
  { id: 65, title: "Palazzo", artist: "Spinall ft. Asake", album: "Top Boy", duration: "3:06", genre: "Afrobeats" },
  { id: 66, title: "Amapiano", artist: "Sarz ft. Asake & Gunna", album: "Single", duration: "2:44", genre: "Afrobeats" },
  { id: 67, title: "Who Is Your Guy?", artist: "Spyro ft. Tiwa Savage", album: "Single", duration: "3:32", genre: "Afrobeats" },
  { id: 68, title: "Overloading (OVERDOSE)", artist: "Mavin All Stars", album: "Chapter X", duration: "3:25", genre: "Afrobeats" },
  { id: 69, title: "Sability", artist: "Ayra Starr", album: "19 & Dangerous Deluxe", duration: "2:46", genre: "Afrobeats" },
  { id: 70, title: "Anoti", artist: "Wizkid", album: "Made in Lagos Deluxe", duration: "3:01", genre: "Afrobeats" },

  // === ANIME SOUNDTRACK SHARE (30 songs) ===
  { id: 71, title: "Gurenge", artist: "LiSA", album: "Demon Slayer Season 1 OP", duration: "3:58", genre: "Anime J-Rock" },
  { id: 72, title: "Zankyou Sanka", artist: "Aimer", album: "Demon Slayer Entertainment District OP", duration: "3:12", genre: "Anime J-Pop" },
  { id: 73, title: "The Rumbling", artist: "SiM", album: "Attack on Titan Final Season Pt 2 OP", duration: "3:40", genre: "Anime Metal" },
  { id: 74, title: "Guren no Yumiya", artist: "Linked Horizon", album: "Attack on Titan OP 1", duration: "5:16", genre: "Anime Rock" },
  { id: 75, title: "Red Swan", artist: "YOSHIKI ft. HYDE", album: "Attack on Titan Season 3 OP", duration: "4:28", genre: "Anime Ballad" },
  { id: 76, title: "KICK BACK", artist: "Kenshi Yonezu", album: "Chainsaw Man OP", duration: "3:13", genre: "Anime Alternative" },
  { id: 77, title: "Unravel", artist: "TK from Ling Tosite Sigure", album: "Tokyo Ghoul OP", duration: "3:58", genre: "Anime J-Rock" },
  { id: 78, title: "Silhouette", artist: "KANA-BOON", album: "Naruto Shippuden OP 16", duration: "4:00", genre: "Anime J-Rock" },
  { id: 79, title: "Blue Bird", artist: "Ikimonogakari", album: "Naruto Shippuden OP 3", duration: "3:35", genre: "Anime J-Pop" },
  { id: 80, title: "Sign", artist: "FLOW", album: "Naruto Shippuden OP 6", duration: "3:55", genre: "Anime J-Rock" },
  { id: 81, title: "GO!!!", artist: "FLOW", album: "Naruto OP 4", duration: "3:59", genre: "Anime J-Rock" },
  { id: 82, title: "Again", artist: "YUI", album: "Fullmetal Alchemist: Brotherhood OP 1", duration: "4:15", genre: "Anime J-Rock" },
  { id: 83, title: "Rain", artist: "SID", album: "Fullmetal Alchemist: Brotherhood OP 5", duration: "4:14", genre: "Anime J-Rock" },
  { id: 84, title: "Shinzou wo Sasageyo!", artist: "Linked Horizon", album: "Attack on Titan Season 2 OP", duration: "5:41", genre: "Anime Rock" },
  { id: 85, title: "Inferno", artist: "Mrs. GREEN APPLE", album: "Fire Force OP", duration: "3:32", genre: "Anime J-Rock" },
  { id: 86, title: "Cry Baby", artist: "Official HIGE DANdism", album: "Tokyo Revengers OP", duration: "3:35", genre: "Anime J-Pop" },
  { id: 87, title: "Idol", artist: "YOASOBI", album: "Oshi no Ko OP", duration: "3:33", genre: "Anime J-Pop" },
  { id: 88, title: "Bling-Bang-Bang-Born", artist: "Creepy Nuts", album: "Mashle: Magic and Muscles Season 2 OP", duration: "2:48", genre: "Anime J-HipHop" },
  { id: 89, title: "Vivid Vice", artist: "Who-ya Extended", album: "Jujutsu Kaisen OP 2", duration: "3:05", genre: "Anime J-Rock" },
  { id: 90, title: "Specialz", artist: "King Gnu", album: "Jujutsu Kaisen Season 2 Shibuya Arc OP", duration: "3:58", genre: "Anime J-Rock", audio: "https://open.spotify.com/track/0GWNtMohuYUEHVZ40tcnHF?si=2dd6aa8f4fdb47a0" },
  { id: 91, title: "Black Catcher", artist: "Vickeblanka", album: "Black Clover OP 10", duration: "3:37", genre: "Anime J-Rock" },
  { id: 92, title: "Black Rover", artist: "Vickeblanka", album: "Black Clover OP 3", duration: "3:20", genre: "Anime J-Rock" },
  { id: 93, title: "Polaris", artist: "BLUE ENCOUNT", album: "My Hero Academia Season 4 OP", duration: "4:01", genre: "Anime J-Rock" },
  { id: 94, title: "The Day", artist: "Porno Graffitti", album: "My Hero Academia OP 1", duration: "4:01", genre: "Anime J-Rock" },
  { id: 95, title: "Odd Future", artist: "UVERworld", album: "My Hero Academia Season 3 OP", duration: "3:44", genre: "Anime J-Rock" },
  { id: 96, title: "Peace Sign", artist: "Kenshi Yonezu", album: "My Hero Academia Season 2 OP", duration: "4:02", genre: "Anime J-Rock" },
  { id: 97, title: "Crossing Field", artist: "LiSA", album: "Sword Art Online OP 1", duration: "4:09", genre: "Anime J-Rock" },
  { id: 98, title: "Sparkle", artist: "RADWIMPS", album: "Your Name.", duration: "8:54", genre: "Anime Soundtrack" },
  { id: 99, title: "Zenzenzense", artist: "RADWIMPS", album: "Your Name.", duration: "4:45", genre: "Anime J-Rock" },
  { id: 100, title: "Suzume", artist: "RADWIMPS ft. Toaka", album: "Suzume", duration: "3:58", genre: "Anime Soundtrack" },
  { id: 101, title: "Energy", artist: "Fireboy DML", album: "Single", duration: "3:25", genre: "Afrobeats", audio: "https://res.cloudinary.com/uhsuzy6c/video/upload/v1784979705/Fireboy-DML-Energy-Audio-_JustNaija.com_ug2hge.mp3", cover: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80" },
  { id: 102, title: "Hallelu", artist: "Masterkraft ft. Bella Shmurda & Zlatan", album: "Hallelu", duration: "3:33", genre: "Afrobeats", audio: "https://res.cloudinary.com/uhsuzy6c/video/upload/v1784984586/Masterkraft_ft_Zlatan_Bella_Shmurda_-_Hallelu_oncmly.mp3", cover: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80" },
  { id: 103, title: "Isaka", artist: "Ciza ft. Tems, Omah Lay & Rema", album: "Isaka", duration: "3:33", genre: "Afrobeats", audio: "https://res.cloudinary.com/uhsuzy6c/video/upload/v1784984875/Ciza-Ft-Tems-Omah-Lay-Thukuthela-Jazzworx-Lekaa-Beats-Isaka-II-6am_zy3dn1.mp3", cover: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80" },
  { id: 104, title: "cana", artist: "seyi vibez", album: "", duration: "2:20", genre: "afrobeats", audio: "https://res.cloudinary.com/uhsuzy6c/video/upload/v1784988441/Seyi-Vibez-Cana_m4cpjr.mp3", cover: "https://images.unsplash.com/photo-14932254f7125-ac70b4814696?w=600&auto=format&fit=crop&q=80" },
  { id: 105, title: "girlfriend", artist: "ruger", album: "", duration: "3:17", genre: "afrobeats", audio: "https://res.cloudinary.com/uhsuzy6c/video/upload/v1784988452/Ruger-Girlfriend_zlpmy4.mp3", cover: "https://images.unsplash.com/photo-1582718094514-299e397b6d4e?w=600&auto=format&fit=crop&q=80" },
  { id: 106, title: "Alaska", artist: "Seyi vibez", album: "", duration: "2:51", genre: "afrobeats", audio: "https://res.cloudinary.com/uhsuzy6c/video/upload/v1784988425/Seyi-Vibez-Alaska_lbbvhx.mp3", cover: "https://images.unsplash.com/photo-1681374500737-044f9777085d?w=600&auto=format&fit=crop&q=80" },
  { id: 107, title: "baby", artist: "joeboy", album: "baby", duration: "2:38", genre: "afrobeats", audio: "https://res.cloudinary.com/uhsuzy6c/video/upload/v1784988415/Joeboy-Baby_cshdhq.mp3", cover: "https://images.unsplash.com/photo-1516802271374-f53d88fc686d?w=600&auto=format&fit=crop&q=80" }
];

module.exports = songs;